import type { Edge, Node } from "reactflow";
import type { ThoughtLoop } from "./types";

export const thoughtLoopDummyData: ThoughtLoop[] = [
  {
    id: "fear-judgment",
    title: "Fear of Judgment",
    description: "Social evaluation turns into self-monitoring and withdrawal.",
    trigger: "A visible moment where others may evaluate performance.",
    coreThought: "If I am imperfect, I will be rejected.",
    emotion: "Anxious vigilance.",
    bodySignal: "Tight chest, warm face.",
    behavior: "Over-edit, over-prepare, then avoid visibility.",
    reinforcement: "Avoidance lowers risk short-term and confirms the fear.",
    interruption: "Share one imperfect draft before certainty arrives.",
    distortionPattern: "Mind reading + identity fusion",
    distortionType: "Mind reading",
    intensity: 4,
    repeatCount: 17,
    repetitionStrength: 4,
    cognitiveLoad: 72,
    energyCost: 14,
    perceivedChoices: ["Say nothing", "Polish longer", "Ask for reassurance"],
    actualOutcome: "Avoidance preserves the same fear narrative.",
    beliefStrength: 4,
    metaphorTheme: "mirror",
    accent: "#60d5d7",
    relatedLoops: ["control", "validation"],
    microThoughts: ["Did they notice that mistake?", "I need one more revision.", "Not ready yet."],
    observerInsights: ["Perfection is functioning as protection.", "Visibility fear is shaping behavior."],
    mirrorChain: {
      event: "Manager gave short feedback.",
      reflections: [
        "Maybe they were unhappy.",
        "I probably missed something obvious.",
        "I keep disappointing people.",
        "Maybe I am not strong enough for this.",
      ],
      distortionLabels: ["Ambiguity bias", "Exaggeration", "Global labeling", "Identity fusion"],
    },
    nodes: [
      { id: "fj-trigger", label: "Trigger", text: "Public attention appears." },
      { id: "fj-thought", label: "Thought", text: "I must not be seen failing." },
      { id: "fj-emotion", label: "Emotion", text: "Threat scanning rises." },
      { id: "fj-behavior", label: "Behavior", text: "Hide, edit endlessly, stall." },
      { id: "fj-reinforcement", label: "Reinforcement", text: "No exposure, no disproof." },
      { id: "fj-interrupt", label: "Interruption", text: "Publish one honest version." },
    ],
  },
  {
    id: "overthinking",
    title: "Overthinking Before Action",
    description: "Analysis expands until momentum disappears.",
    trigger: "A meaningful task with uncertain outcome.",
    coreThought: "I must solve every risk first.",
    emotion: "Cognitive overload and hesitation.",
    bodySignal: "Mental fog and forehead pressure.",
    behavior: "Research loops replace execution.",
    reinforcement: "Delay feels safe and therefore justified.",
    interruption: "Run a 20-minute experiment now.",
    distortionPattern: "Future catastrophizing",
    distortionType: "Catastrophizing",
    intensity: 3,
    repeatCount: 23,
    repetitionStrength: 5,
    cognitiveLoad: 81,
    energyCost: 12,
    perceivedChoices: ["Research more", "Plan longer", "Delay start"],
    actualOutcome: "Delayed action and temporary relief repeat the loop.",
    beliefStrength: 3,
    metaphorTheme: "trail",
    accent: "#9a7cf4",
    relatedLoops: ["control", "avoidance"],
    microThoughts: ["I need one more framework.", "Still not enough clarity.", "Action can wait."],
    observerInsights: ["Complexity is delaying commitment.", "No step is small enough yet."],
    mirrorChain: {
      event: "Need to start important work.",
      reflections: [
        "I should first be fully ready.",
        "I still do not know enough.",
        "If I act now, I could ruin momentum.",
        "Maybe I am not disciplined enough.",
      ],
      distortionLabels: ["Readiness trap", "Certainty demand", "Catastrophizing", "Identity conclusion"],
    },
    nodes: [
      { id: "ot-trigger", label: "Trigger", text: "Important task appears." },
      { id: "ot-thought", label: "Thought", text: "More clarity is required first." },
      { id: "ot-emotion", label: "Emotion", text: "Unease masked as logic." },
      { id: "ot-behavior", label: "Behavior", text: "Collect, compare, postpone." },
      { id: "ot-reinforcement", label: "Reinforcement", text: "No action means no failure." },
      { id: "ot-interrupt", label: "Interruption", text: "Choose a smallest executable step." },
    ],
  },
  {
    id: "control",
    title: "Need for Control",
    description: "Uncertainty becomes rigidity and over-management.",
    trigger: "Ambiguous timing or unanswered outcomes.",
    coreThought: "If I do not control this, it will collapse.",
    emotion: "Pressure and hyper-alertness.",
    bodySignal: "Jaw tension and shallow breath.",
    behavior: "Micromanage details, re-check repeatedly.",
    reinforcement: "Temporary certainty rewards control habits.",
    interruption: "Define influenceable variables and release the rest.",
    distortionPattern: "Responsibility inflation",
    distortionType: "Control bias",
    intensity: 5,
    repeatCount: 19,
    repetitionStrength: 4,
    cognitiveLoad: 88,
    energyCost: 16,
    perceivedChoices: ["Re-check everything", "Take over tasks", "Delay delegation"],
    actualOutcome: "Short-term certainty increases control dependence.",
    beliefStrength: 5,
    metaphorTheme: "vortex",
    accent: "#d79ab0",
    relatedLoops: ["overthinking", "validation"],
    microThoughts: ["Check once more.", "What if I missed something?", "Control means safety."],
    observerInsights: ["Relief rewards rigidity.", "Trust is replaced by monitoring."],
    mirrorChain: {
      event: "Timeline became uncertain.",
      reflections: [
        "I need to track every detail.",
        "If I stop checking, things will break.",
        "Only I can hold this together.",
        "If this fails, it proves I am careless.",
      ],
      distortionLabels: ["Control bias", "Catastrophic prediction", "Burden centralization", "Identity attack"],
    },
    nodes: [
      { id: "ct-trigger", label: "Trigger", text: "Unclear outcome emerges." },
      { id: "ct-thought", label: "Thought", text: "Control equals safety." },
      { id: "ct-emotion", label: "Emotion", text: "Compressed urgency." },
      { id: "ct-behavior", label: "Behavior", text: "Grip harder and monitor all." },
      { id: "ct-reinforcement", label: "Reinforcement", text: "Relief reinforces rigidity." },
      { id: "ct-interrupt", label: "Interruption", text: "Practice strategic non-control." },
    ],
  },
  {
    id: "validation",
    title: "Validation Seeking",
    description: "External reassurance becomes emotional regulation.",
    trigger: "Silence or delayed feedback.",
    coreThought: "Without confirmation, I am uncertain of worth.",
    emotion: "Restless insecurity.",
    bodySignal: "Stomach flutter, restless hands.",
    behavior: "Check responses, seek repeated reassurance.",
    reinforcement: "Relief from praise makes checking automatic.",
    interruption: "Self-validate before checking outward.",
    distortionPattern: "External-worth dependency",
    distortionType: "Validation dependency",
    intensity: 4,
    repeatCount: 26,
    repetitionStrength: 5,
    cognitiveLoad: 76,
    energyCost: 13,
    perceivedChoices: ["Refresh messages", "Send follow-up", "Ask for reassurance"],
    actualOutcome: "Relief arrives briefly, then uncertainty returns.",
    beliefStrength: 4,
    metaphorTheme: "vortex",
    accent: "#76d8c6",
    relatedLoops: ["fear-judgment", "control"],
    microThoughts: ["Why no reply yet?", "Did I say too much?", "I need confirmation now."],
    observerInsights: ["Silence is interpreted as rejection.", "Checking creates temporary relief, then repeats."],
    mirrorChain: {
      event: "They did not reply yet.",
      reflections: [
        "Maybe I said something wrong.",
        "They are ignoring me.",
        "People lose interest quickly.",
        "I am not worth much.",
      ],
      distortionLabels: ["Mind reading", "Negative assumption", "Generalization", "Identity fusion"],
    },
    nodes: [
      { id: "vs-trigger", label: "Trigger", text: "Feedback lag appears." },
      { id: "vs-thought", label: "Thought", text: "Maybe I did not matter." },
      { id: "vs-emotion", label: "Emotion", text: "Need for reassurance spikes." },
      { id: "vs-behavior", label: "Behavior", text: "Refresh, ask, over-explain." },
      { id: "vs-reinforcement", label: "Reinforcement", text: "Response soothes uncertainty." },
      { id: "vs-interrupt", label: "Interruption", text: "Anchor in internal evidence first." },
    ],
  },
  {
    id: "avoidance",
    title: "Avoidance / Procrastination",
    description: "Stress converts to delay and short-term relief.",
    trigger: "A task tied to possible disappointment.",
    coreThought: "If I start, I might prove I cannot do it.",
    emotion: "Dread with low-grade shame.",
    bodySignal: "Heavy limbs and breath holding.",
    behavior: "Distract, defer, choose low-stakes tasks.",
    reinforcement: "Immediate relief rewards postponement.",
    interruption: "Start for five minutes with no outcome demand.",
    distortionPattern: "Failure-identity fusion",
    distortionType: "Identity fusion",
    intensity: 3,
    repeatCount: 31,
    repetitionStrength: 5,
    cognitiveLoad: 69,
    energyCost: 11,
    perceivedChoices: ["Do low-stakes tasks", "Research first", "Wait for motivation"],
    actualOutcome: "Delay lowers fear briefly while growing resistance.",
    beliefStrength: 3,
    metaphorTheme: "trail",
    accent: "#8fb4ff",
    relatedLoops: ["overthinking", "fear-judgment"],
    microThoughts: ["I will start after one more task.", "Not in the right state.", "Later is safer."],
    observerInsights: ["Relief from delay is mistaken for strategy.", "Initiation friction is emotional."],
    mirrorChain: {
      event: "A difficult task appears on calendar.",
      reflections: [
        "I should clear smaller tasks first.",
        "I am not in the right state yet.",
        "If I start and fail, confidence drops.",
        "Maybe I am just not capable enough.",
      ],
      distortionLabels: ["Priority displacement", "State dependency", "Failure magnification", "Identity conclusion"],
    },
    nodes: [
      { id: "av-trigger", label: "Trigger", text: "Demanding task arrives." },
      { id: "av-thought", label: "Thought", text: "Starting risks exposure." },
      { id: "av-emotion", label: "Emotion", text: "Dread and resistance." },
      { id: "av-behavior", label: "Behavior", text: "Delay through substitutions." },
      { id: "av-reinforcement", label: "Reinforcement", text: "Relief proves delay worked." },
      { id: "av-interrupt", label: "Interruption", text: "Begin before confidence." },
    ],
  },
];

export function buildSandboxNodes(loop: ThoughtLoop): Node[] {
  const labels = ["Trigger", "Thought", "Emotion", "Action", "Reinforcement"];
  const positions = [
    { x: 40, y: 80 },
    { x: 250, y: 20 },
    { x: 460, y: 80 },
    { x: 460, y: 220 },
    { x: 250, y: 280 },
  ];

  return labels.map((label, index) => ({
    id: `lab-${loop.id}-${label.toLowerCase()}`,
    type: "default",
    data: { label },
    position: positions[index],
    style: {
      borderRadius: 12,
      padding: 10,
      color: "#f0ecde",
      border: "1px solid rgba(255,255,255,0.18)",
      background: "rgba(20, 26, 46, 0.7)",
      boxShadow: "0 8px 24px rgba(0,0,0,0.35)",
      fontSize: 12,
      letterSpacing: "0.04em",
      width: 150,
      textAlign: "center",
    },
  }));
}

export function buildSandboxEdges(loop: ThoughtLoop): Edge[] {
  const key = `lab-${loop.id}`;
  return [
    { id: `${key}-1`, source: `${key}-trigger`, target: `${key}-thought`, animated: true, style: { stroke: "#66d8d1" } },
    { id: `${key}-2`, source: `${key}-thought`, target: `${key}-emotion`, animated: true, style: { stroke: "#8f79ee" } },
    { id: `${key}-3`, source: `${key}-emotion`, target: `${key}-action`, animated: true, style: { stroke: "#d68db7" } },
    {
      id: `${key}-4`,
      source: `${key}-action`,
      target: `${key}-reinforcement`,
      animated: true,
      style: { stroke: "#7ecbe4" },
    },
    {
      id: `${key}-5`,
      source: `${key}-reinforcement`,
      target: `${key}-trigger`,
      animated: true,
      style: { stroke: "#5fd4c9" },
    },
  ];
}
